### ISSUE TITLE
[Bug] v1.2.1 has dependency conflict

### ISSUE THREAD

**Issue by chrismcb** [creativetimofficial/ct-nextjs-material-kit-pro#26] opened 2022-09-01 08:19 UTC
### Version
1.2.1
### Reproduction link
http://example.com/no/minimal/repro
### Operating System
Windows 10
### Device
Dell laptop
### Browser & Version
No browser
### Steps to reproduce
Download v1.2.1 and unzip it
in folder run "npm install"
### What is expected?
the install succeeds
### What is actually happening?
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nextjs-material-kit-pro@1.2.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR!   @material-ui/core@"4.11.4" from the root project

---
### Solution
No current solution. I installed using --legacy-peer-deps but I'm wary abut doing so.
I guess I could change package.json to load the last v17 of react.
### Additional comments
As I understand it material-ui/core doesn't work with react 18.  And I believe react 18 has some breaking changes, and it only works material v5. So I don't see how this will work.

**Comment by sajadevo** [comment] 2022-09-02 07:11
Hi @chrismcb,

Could you please provide me an image of the issue?

Regards,
Sajad

**Comment by chrismcb** [comment] 2022-09-02 07:40
I'm not sure what more info you need, the "what is actually happening section" should give you enough. A bit more of the message:

```
C:\frontend> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nextjs-material-kit-pro@1.2.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"4.11.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\chrismcb.000\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chrismcb.000\AppData\Local\npm-cache\_logs\2022-09-01T09_30_08_801Z-debug-0.log
```


I tried to change react to 17.0.2 then I got this:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.5
npm ERR! node_modules/react-animate-on-scroll
npm ERR!   react-animate-on-scroll@"2.1.5" from the root project
```

So then I changed it to 17.0.0 and got this:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR! node_modules/next
npm ERR!   next@"12.2.5" from the root project
```

At that point I gave up and installed it using --legacy-peer-deps
But the issue is @material-ui/core@4.11.4 wants react 16 or 17 and not 18.

**Comment by sajadevo** [comment] 2022-09-09 08:16
Hi @chrismcb,

I got it it's not only the @material-ui/core there are too many packages that doesn't supports React 18 but our users want to have React 18 so for the moment please kindly use the `--legacy-peer-deps` until I fix that issue.

Regards,
Sajad

**Comment by tinhphamvan** [comment] 2022-09-12 01:15
@sajadevo did you fix this issue?

**Comment by sajadevo** [comment] 2022-09-12 05:51
> @sajadevo did you fix this issue? can you upgrade @mui to v5 also?

@tinhphamvan,

Migration to mui v5 won't happen because we'll release a new version of the product NextJS Material Kit 2 PRO which will use the latest packages and for this one we'll only fix the issues with packages that cause conflict.

Regards,
Sajad

**Comment by mattmcegg** [comment] 2022-09-28 15:10
This worked (npm i --legacy-peer-deps), but then I had to start the server with "npm run dev" not "npm start" like the documentation states. Not sure if this is related to legacy deps or not. 

When is "NextJS Material Kit 2 PRO" being released?

**Comment by sajadevo** [comment] 2022-09-29 08:56
Hey @mattmcegg,

You need to run `npm run dev` not `start` because it's next.js not CRA. The NextJS Material Kit 2 PRO release date is not clear yet.

Regards,
Sajad

**Comment by mattmcegg** [comment] 2022-09-29 13:56
@sajadevo The documentation says to run `npm start`: https://demos.creative-tim.com/nextjs-material-kit-pro/documentation/tutorial

**Comment by sajadevo** [comment] 2022-09-30 11:02
Hey @mattmcegg,

Thank you for letting me know about that issue, I'll marked it as a documentation issue so to fix it in the future.

Regards,
Sajad

**Comment by erichkuba** [comment] 2022-10-26 20:55
I've literally just purchased this product today (company licence) and am disappointed to be facing these dependency issues without a resolution in sight. When will "NextJS Material Kit 2 PRO" be available, and if you are not going to fix the current product, will an upgrade path be provided? I'm happy to take this discussion offline if you prefer.

**Comment by sajadevo** [comment] 2022-10-28 07:15
Hey @erichkuba,

Could you please send me the issue image that you're getting, because the v2 version is not clear that when will happen.

Regards,
Sajad

**Comment by erichkuba** [comment] 2022-10-30 18:54
Hey @sajadevo,

The issue is exactly as reported by @chrismcb. The template dependencies are broken and should not require us, as paying customers, to carry the risk of these potentially breaking changes due to us forcing package dependencies _(especially given that there is no automated test coverage)_.

I understand that customers may have pressured you to deliver React 18 support; however, if that upgrade were not possible _(due to the issues with broken dependencies that we're experiencing)_, then it would have been better to have kept the template on an older version of React/NextJS whilst maintaining a functional dependency tree.

I'm afraid that as things stand right now, I'm not a happy customer, given that we spent a considerable amount of money on the template and that we're now having to spend additional money to fix it. Please advise if you can remedy this situation so we can work with you to get to a resolution.

Kind regards,

Erich

**Comment by erichkuba** [comment] 2022-11-11 16:17
@sajadevo It has been 12 days since I requested a resolution. I paid for premium support when I purchased the product. Please be so good as to either reply or to cancel the order and reverse the transaction, and I'll find a template from someone who actually does support their customers. This is unusable, and we must move ahead.

**Comment by chrismcb** [comment] 2022-11-11 16:35
If you do find another template, please let me know!

**Comment by sajadevo** [comment] 2022-11-14 07:38
> @sajadevo It has been 12 days since I requested a resolution. I paid for premium support when I purchased the product. Please be so good as to either reply or to cancel the order and reverse the transaction, and I'll find a template from someone who actually does support their customers. This is unusable, and we must move ahead.

@erichkuba I already mentioned that the `npm i --legacy-peer-deps` can solve this issue is there's any other issue please lemme know so that I can assist you.

Regards,
Sajad

**Comment by erichkuba** [comment] 2022-11-14 14:33
@sajadevo Can we please have access to the product prior to the upgrade to React 18? I would like us to evaluate which is the lesser evil; living with these broken dependencies or downgrading react.

**Comment by sajadevo** [comment] 2022-11-15 10:21
> @sajadevo Can we please have access to the product prior to the upgrade to React 18? I would like us to evaluate which is the lesser evil; living with these broken dependencies or downgrading react.

@erichkuba I've marked this issues as urgent fix and I'll update the entire product on 21 of November next week Monday.

Regards,
Sajad

**Comment by erichkuba** [comment] 2022-11-15 14:40
Thank you. I look appreciate that and look forward to hearing from you tomorrow. We will make time to test it as soon as the update comes through.

**Comment by sajadevo** [comment] 2022-11-16 06:11
Hey @erichkuba,

I've released the new update you can check it and lemme know if you still face with any issue.

Regards,
Sajad

**Comment by erichkuba** [comment] 2022-11-16 16:06
Hey @sajadevo,

We've had a quick cursory look at the package, and it looks positive, which is brilliant. Thank you.

We'll get back to the creation of the website that will use this template next week, and I may have further comments once we get into that, but some initial thoughts that you may want to consider follow:

1. `.npmrc` content seems to be superfluous now that the dependencies are fixed, and I suggest deleting the file.

2. We updated dependencies to the latest minor changes using `ncu --target minor u` and everything seems to work just fine.  The effect to `package.json` is:

```
 "dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/icons-material": "^5.10.14",
    "@mui/material": "^5.10.14",
    "@mui/styles": "^5.10.14",
    "animate.css": "4.1.1",
    "classnames": "2.3.2",
    "moment": "2.29.4",
    "next": "12.3.3",
    "nouislider": "15.6.1",
    "prop-types": "15.8.1",
    "react": "18.2.0",
    "react-animate-on-scroll": "2.1.5",
    "react-datetime": "3.2.0",
    "react-dom": "18.2.0",
    "react-image-gallery": "1.2.11",
    "react-slick": "0.29.0",
    "react-tagsinput": "3.20.0",
    "sass": "1.56.1",
    "webpack": "5.75.0"
  },
```

3. Looking at the console warning `"Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot"` raised on each page change. An initial fix, which we thought we'd submit for your consideration, look something like the attached `_app.js` file. Hope it helps.

[ReactDOM.render.fix.zip](https://github.com/creativetimofficial/ct-nextjs-material-kit-pro/files/10023477/ReactDOM.render.fix.zip)

**Comment by sajadevo** [comment] 2022-11-18 07:54
> Hey @sajadevo,
> 
> We've had a quick cursory look at the package, and it looks positive, which is brilliant. Thank you.
> 
> We'll get back to the creation of the website that will use this template next week, and I may have further comments once we get into that, but some initial thoughts that you may want to consider follow:
> 
> 1. `.npmrc` content seems to be superfluous now that the dependencies are fixed, and I suggest deleting the file.
> 2. We updated dependencies to the latest minor changes using `ncu --target minor u` and everything seems to work just fine.  The effect to `package.json` is:
> 
> ```
>  "dependencies": {
>     "@emotion/react": "^11.10.5",
>     "@emotion/styled": "^11.10.5",
>     "@mui/icons-material": "^5.10.14",
>     "@mui/material": "^5.10.14",
>     "@mui/styles": "^5.10.14",
>     "animate.css": "4.1.1",
>     "classnames": "2.3.2",
>     "moment": "2.29.4",
>     "next": "12.3.3",
>     "nouislider": "15.6.1",
>     "prop-types": "15.8.1",
>     "react": "18.2.0",
>     "react-animate-on-scroll": "2.1.5",
>     "react-datetime": "3.2.0",
>     "react-dom": "18.2.0",
>     "react-image-gallery": "1.2.11",
>     "react-slick": "0.29.0",
>     "react-tagsinput": "3.20.0",
>     "sass": "1.56.1",
>     "webpack": "5.75.0"
>   },
> ```
> 
> 3. Looking at the console warning `"Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot"` raised on each page change. An initial fix, which we thought we'd submit for your consideration, look something like the attached `_app.js` file. Hope it helps.
> 
> [ReactDOM.render.fix.zip](https://github.com/creativetimofficial/ct-nextjs-material-kit-pro/files/10023477/ReactDOM.render.fix.zip)

Hey @erichkuba,

Happy to hear that related to your options.

1. The .npmrc is a good option it helps you to don't crash the app in the future if there is any conflict between the versions of dependencies.
2. Good you can update all the dependencies based on your needs.
3. I'll fix this issue as well.

Anyway we're working hard to improve the products more because most of the products built by someone who is not working with us anymore and there we face with lot's of problems and we're doing to make a base structure for a better developer and user experience.

Regards,
Sajad

**Closed by sajadevo** 2022-11-18 07:54 UTC
Labels: documentation
